all: clean clone

clone:
	-git clone git@github.com:desantis/rplmaster.git
	-git clone git@github.com:desantis/jk2mv.git
	-git clone git@github.com:desantis/mvsdk.git
	-git clone git@github.com:desantis/libzt.git

clean:
	-rm -rf jk2mv
	-rm -rf libzt
	-rm -rf mvsdk
	-rm -rf rplmaster
